added (beta) inbound webhook support

diff --git a/bin/pm b/bin/pm
--- a/bin/pm
+++ b/bin/pm
@@ -55,6 +55,10 @@ opts:scanopts(){
         LOG=1
         shift
         ;;
+      -h)
+        ALL=1
+        shift
+        ;;
     esac
   done
 }
@@ -62,7 +66,7 @@ opts:scanopts(){
 opts:scancmd(){
   for arg in $@; do
     case $arg in
-      exec|start|stop|restart|startall|stopall|list|inspect|status|tail)
+      exec|debug|start|stop|restart|startall|stopall|list|inspect|status|tail)
         scope=process
         cmd=$arg
         break
@@ -75,6 +79,11 @@ opts:scancmd(){
       config)
         scope=config
         cmd=edit
+        break
+        ;;
+      server)
+        scope=server
+        cmd=start
         break
         ;;
     esac
@@ -97,6 +106,11 @@ string:urlencode(){
     encoded="$encoded""$o"
   done
   echo "${encoded}"
+}
+
+
+string:wraplines(){
+  cat | cut -c 1-$(tput cols)
 }
 
 event:trigger_analytics(){
@@ -200,7 +214,7 @@ process:getpid(){
   local pidfile=$(process:getpidfile $appname)
   if [[ -f $pidfile ]]; then
     cat $pidfile
-  else 
+  else
     echo -1
   fi
 }
@@ -219,18 +233,19 @@ process:getlogfile(){
 
 process:exec(){
   local appname="${1}"
-  shift 
+  shift
   cnt=0
   lockfile=$(process:getlockfile $appname)
   deffile=$(process:gettmpfile $appname).def
   cntfile=$(process:gettmpfile $appname).cnt
   workdir=$(apps:getworkdir $deffile)
+  startcmd=$(apps:getstartcmd $deffile)
   cd $workdir
   trap "process:log \"#$cnt: $appname killed \$?\"; pkill -P $$" EXIT SIGHUP SIGINT SIGTERM
   echo $cnt > $cntfile
   while :; do
-    process:log "#$cnt $appname started [pid $$]"
-    { flock -w 0 $lockfile "$@" || exit 1;} 
+    process:log "#$cnt $appname started [pid $$]: ${startcmd}"
+    { flock -w 0 $lockfile ${startcmd} || exit 1;}
     code="$?"                                 # check exit status code
     exit="EXIT"
     if [[ $code == 129 ]]; then
@@ -248,10 +263,10 @@ process:exec(){
     sleep 5s                                  # wait for seconds until next boot
     cnt=$(($cnt+1))                           # increment counter
     echo $cnt > $cntfile
-    # handle odd/buggy case 
+    # handle odd/buggy case
     if [[ $cnt -gt 50 ]]; then
     event:trigger $appname error "restarted > 50 times"
-      $selfpath/pm stop $appname              
+      $selfpath/pm stop $appname
     fi
   done
 }
@@ -278,6 +293,7 @@ process:inspect(){
   echo "logfile stderr         : "$logfile.stderr
   echo "lockfile               : "$lockfile
   echo "pidvalue               : "$pidvalue
+  echo "repository             : "$(process:getrepo $appname)
   set > $tmpfile.1
   if [[ -f $workdir/env.sh ]]; then
     source $workdir/env.sh
@@ -309,15 +325,14 @@ process:start(){
   pidfile=$(process:gettmpfile $appname).pid
   logfile=$(process:getlogfile $appname)
   lockfile=$(process:getlockfile $appname)
-  startcmd=$(apps:getstartcmd $deffile)
   flock -w 0 $lockfile sleep 0.1s || { echo "already started"; exit 1; }
-  nohup $selfpath/pm exec $appname ${startcmd} 1>$logfile.stdout 2>$logfile.stderr &
-  echo $! > $pidfile 
+  nohup $selfpath/pm exec $appname 1>$logfile.stdout 2>$logfile.stderr &
+  echo $! > $pidfile
+  echo "'$appname' started'"
+  event:trigger $appname start
   if [[ -n $LOG ]]; then
     process:tail $appname
   fi
-  echo "'$appname' started'"
-  event:trigger $appname start
 }
 
 process:tail(){
@@ -326,7 +341,7 @@ process:tail(){
   deffile=$(process:gettmpfile $appname).def
   logfile=$(process:getlogfile $appname)
   echo -e "press CTRL-C to stop logmonitor:\n"
-  tailf $logfile.stdout $logfile.stderr
+  tail -q -f $logfile.*
 }
 
 process:stop(){
@@ -334,7 +349,7 @@ process:stop(){
   shift # remove first arg
   pid=$(process:getpid $appname)
   if [[ ! $pid == "-1" ]]; then
-    echo killing pid $pid 
+    echo killing pid $pid
     rm $(process:getpidfile $appname)
     pkill -P $pid
   else
@@ -347,7 +362,7 @@ process:restart(){
   local appname="${1}"
   event:trigger $appname restart
   process:stop $appname &
-  wait 
+  wait
   process:start $appname
 }
 
@@ -357,7 +372,6 @@ process:ps(){
   lockfile=$(process:getlockfile $appname)
   cntfile=$(process:gettmpfile $appname).cnt
   ps="$(ps au)"
-  cols="$(echo "$ps" | head -n1)"                        # print cols header
   set +e
   psapp="$(echo "$ps" | fgrep $appname | fgrep flock)"
   restarts=0
@@ -367,11 +381,12 @@ process:ps(){
   status="stopped"
   port="none"
   echo "$ps" | fgrep -q "pm exec $appname" && status="running"
-  printf "%-15s %-8s %-6s %-10s %s\n\n" "APP" "STATUS" "PORT" "RESTARTS" "$cols"
-  printf "%-15s %-8s %-6s %-10s %s\n" "$appname" "$status" $port $restarts "$psapp"
+  printf "%-15s %-8s %-6s %-10s %s\n" "$appname" "$status" $port $restarts "$psapp" | string:wraplines
 }
 
 process:status(){
+  cols="$(ps au | head -n1)"                        # print cols header
+  printf "%-15s %-8s %-6s %-10s %s\n\n" "APP" "STATUS" "PORT" "RESTARTS" "$cols"
   apps:every process:ps
 }
 
@@ -385,12 +400,18 @@ process:getrepo(){
   deffile=$(process:gettmpfile $appname).def
   workdir=$(apps:getworkdir $deffile)
   cd $workdir
-  if [[ -f .git/config  ]]; then
+  if [[ -f .git/config ]]; then
     repo="$( cat .git/config | grep url | head -n1 | sed 's/.*\///g' )"
     branch="$( git branch 2>&1 | grep "^*" | sed 's/ //g;s/^*//g'   )"
     hash="$(git rev-parse HEAD 2>/dev/null)"
     echo "$repo(${branch}:${hash:0:4})"
   fi
+}
+
+process:debug(){
+  local appname="${1}"
+  process:inspect $appname
+  process:exec $appname
 }
 
 
@@ -404,6 +425,7 @@ apps:init(){
   local silent="${1}"
   if [[ ! -d $app_config_dir ]]; then
     mkdir -p $app_config_dir/apps
+    echo "$selfpath/pm webserver" > $app_config_dir/apps/pmserver.def
   fi
 }
 
@@ -444,10 +466,9 @@ apps:getstartcmd(){
   appdeffile="$(<$appdef)"
   if [[ $appdeffile =~ (.*package.json$) ]]; then
     echo "npm start"
+    return 0
   fi
-  if [[ $appdeffile =~ (.*app.sh$) ]]; then
-    echo $appdeffile
-  fi
+  echo $appdeffile # app.sh or anything shell
 }
 
 apps:every(){
@@ -458,7 +479,7 @@ apps:every(){
     $cb $appname $apppath
   done
 }
- 
+
 apps:add(){
   local appdir="${1}"
   app:init
@@ -492,22 +513,48 @@ apps:remove(){
   $selfpath/pm stop $app &>/dev/null
   rm $app_config_dir/apps/$app.*
   echo "'$app' was removed"
-   
- }
+}
+
 
 declare -A config_template
 
-config_template['ga']='# In analytics you can view graphs at:
+config_template["ga"]='# In analytics you can view graphs at:
+#
+#   Realtime->Events
+#   Behaviour->Events->overview
+#
+#   note: please save this file before exiting
+#
+# export CLIENT_NAME="$(cat /etc/hostname)"       # uncomment this if needed
+# export CLIENTID="$APP_NAME"                     # update this if your app has multiple instances
+# export DATASOURCE="$APP_NAME"                   # update this if needed for better stats
 export GOOGLE_ANALYTICS_TOKEN="X-XXXXXXX-1"
 '
 
-config_template['webhook']='# put urls below on each line which can handle POST requests (with json)
+config_template["webhook"]='# put urls below on each line which can handle POST requests (with json)
+#
+# ps. make sure you save this file before exiting
+'
+
+config_template["cmdhook"]='# put cmds (with fullpath like "/usr/bin/foo bar") below on each line which can handle POST requests (with json)
+#
+# ps. make sure you save this file before exiting
+'
+
+config_template["pmserver"]='# specify your http port below
+#
+# ps. make sure you save this file before exiting
+export PORT=8080
 '
 
 config:edit(){
   local config_type="${1}"
   local appname="${2}"
-  apps:exit_if_nonexists $appname
+  if [[ ! $config_type == "pmserver" ]]; then
+    apps:exit_if_nonexists $appname
+  else
+    appname=pmserver
+  fi
   which curl &>/dev/null || { echo "curl doesn't seem to be installed (which is required for this feature)"; exit 1; }
   if [[ ! -n $EDITOR ]]; then
     echo "no default editor set. Please specify using 'export EDITOR=vim' e.g."
@@ -518,7 +565,109 @@ config:edit(){
     echo "${config_template["$config_type"]}" > $configfile
   fi
   $EDITOR $configfile
+  if [[ $config_type == "pmserver" ]]; then
+    server:init
+  fi
 }
+
+
+server:listen(){
+  local port="${1}"
+  which gawk &>/dev/null || { echo "'gawk' is not installed..which is needed for pm.sh"; }
+  while :; do
+    gawk 'BEGIN{
+      SOCK="/inet/tcp/8080/0/0";
+      body_size=0;
+      #request head
+      while( (SOCK |& getline REQ) > 0){
+        print REQ;
+        if( REQ~/^Content-Length/ ){
+          split(REQ,cl,":");
+          body_size=cl[2];
+        }
+        if( REQ~/\r/ ){ break; }
+      }
+      #request body
+      recive_size=0;
+      if(body_size > 0){
+        while( (SOCK |& getline REQ) > 0){
+          print REQ;
+          recive_size=recive_size + length(REQ) + 1;
+          if(recive_size >= body_size){ break; }
+        }
+      }
+      #response
+      RS = ORS = "\r\n"
+      Response = "{\"status\":\"received\"}"
+      Len = length(Response) + length(ORS)
+      print "HTTP/1.0 200"             |& SOCK;
+      print "Content-Length: " Len ORS |& SOCK;
+      print Response                   |& SOCK;
+      system("")
+      close(SOCK);
+    }'
+  done
+}
+
+server:parse_appname(){
+  local postrequest="${1}"
+  local type="${2}"
+  appname="${postrequest/POST \/}"
+  echo "${appname/\/$type*/}"
+}
+
+server:onrequest(){
+  local request="${1}"
+  local appname
+  if [[ $request =~ (POST .*\/start) ]]; then
+    appname=$(server:parse_appname "$request" start)
+    echo $appname
+  fi
+  if [[ $request =~ (POST .*\/pull) ]]; then
+    appname=$(server:parse_appname "$request" pull)
+    deffile=$(process:gettmpfile $appname).def
+    if [[ -f $deffile ]]; then
+      server:gitpull $appname
+    else
+      echo -e "received webhook: pull $appname (error: no such app)"
+    fi
+  fi
+}
+
+server:start(){
+  local port="${1}"
+  # check if we have a commandline invocation
+  if [[ $port == "start" ]]; then
+    if [[ -f $app_config_dir/apps/pmserver.pmserver ]]; then
+      source $app_config_dir/apps/pmserver.pmserver
+      port=$PORT
+    fi
+  fi
+  echo "listening on port $port"
+  server:listen $port | mappipe server:onrequest
+}
+
+server:gitpull(){
+  local appname="${1}"
+  deffile=$(process:gettmpfile $appname).def
+  workdir=$(apps:getworkdir $deffile)
+  if [[ -d $workdir/.git ]]; then
+    cd $workdir
+    echo -e "received webhook: pull $appname, performing git pull"
+    set +e
+    $selfpath/pm stop $appname
+    git pull origin master 2>&1 | awk '{ print "git: "$0 }'
+    $selfpath/pm start $appname
+    set -e
+  else
+    echo -e "received webhook: pull $appname (error: $workdir is not a git repo)"
+  fi
+}
+
+server:init(){
+  echo "$selfpath/pm server start" > $app_config_dir/apps/pmserver.def
+}
+
 
 config_dir=~/.pm.sh
 
@@ -533,7 +682,7 @@ app:init(){
 }
 
 app:help(){
-  echo 'Usage:                                                                                                          '     
+  echo 'Usage:                                                                                                          '
   echo '                                                                                                                '
   echo '  pm init                                      create ~/.pm.conf.sh configfile                                  '
   echo '  pm list                                      list appnames                                                    '
@@ -543,14 +692,25 @@ app:help(){
   echo '  pm start <appname> [--log]                   start app (and tail logs)                                        '
   echo '  pm stop <appname>                            stop  app                                                        '
   echo '  pm startall                                  start all applications                                           '
-  echo '  pm stopall                                   stop all applications                                           '
-  echo '  pm tail <appname>                            monitor logs                                                        '
+  echo '  pm stopall                                   stop all applications                                            '
+  echo '  pm tail <appname>                            monitor logs                                                     '
   echo '  pm inspect <appname>                         show all related files, startcmds, env-vars                      '
+  echo '  pm debug <appname>                           start application in foreground (for testing purposes)           '
   echo '                                                                                                                '
-  echo '  pm config ga <appname>                       configure google analytics (opens default editor)                '
-  echo '  pm config webhook <appname>                  add POST webhook (opens default editor)                          '
-  echo '  pm start config gitwebhook <appname>               add POST webhook (opens default editor)                          '
-  echo '                                                                                                                '
+  if [[ ! -n $ALL ]]; then
+    echo '  type 'pm -h' to see all options: receiving github/bitbucket webhooks, pushing to google analytics etc       '
+  else
+    echo '  pm config ga <appname>                       configure google analytics (opens default editor)              '
+    echo '  pm config webhook <appname>                  [todo] add POST webhooks (opens default editor)                '
+    echo '  pm config cmdhook <appname>                  [todo] add unix commands (opens default editor)                '
+    echo '                                                                                                              '
+    echo '  pm config pmserver <appname>                 set port of server to receive github/bitbucket webhooks        '
+    echo '  pm <start|stop> pmserver [--log]             start/stop server (background) [and watch logs]                '
+    echo '                                                                                                              '
+    echo '  environment variables:                                                                                      '
+    echo '     PM_CONFIG=/my/dir                         configuration path (default: ~/.pm.sh)                         '
+    echo '                                                                                                              '
+  fi
   echo '                                               ┌─────────────────────────────────────────────────┐              '
   echo '                                               │ docs: https://github.com/coderofsalvation/pm.sh │              '
   echo '                                                                                                                '
