work in progress [might break]

diff --git a/bin/pm b/bin/pm
--- a/bin/pm
+++ b/bin/pm
@@ -10,25 +10,17 @@ shopt -s extglob               # regular expressions
 path="$(pwd)"
 selfpath="$( dirname "$(readlink -f "$0")" )"
 tmpfile="/tmp/$(basename $0).tmp.$(whoami)"
-#
-# generated by powscript (https://github.com/coderofsalvation/powscript)
-#
-
-on () 
-{ 
-    func="$1";
-    shift;
-    for sig in "$@";
-    do
-        trap "$func $sig" "$sig";
-    done
-}
-
+which flock &>/dev/null        || { echo "dependency error: it seems 'flock' is not installed (please install it)"; }
+which awk &>/dev/null          || { echo "dependency error: it seems 'awk' is not installed (please install it)"; }
+which date &>/dev/null         || { echo "dependency error: it seems 'date' is not installed (please install it)"; }
+which sleep &>/dev/null        || { echo "dependency error: it seems 'sleep' is not installed (please install it)"; }
+which ps &>/dev/null           || { echo "dependency error: it seems 'ps' is not installed (please install it)"; }
+which head &>/dev/null         || { echo "dependency error: it seems 'head' is not installed (please install it)"; }
 
 scope=app
 cmd=help
 
-for arg in $@; do
+for arg in "$@"; do
   case $arg in
     exec)
       scope=process
@@ -55,6 +47,21 @@ for arg in $@; do
       cmd=$arg
       shift
       ;;
+    init)
+      scope=apps
+      cmd=$arg
+      shift
+      ;;
+    add)
+      scope=apps
+      cmd=$arg
+      shift
+      ;;
+    remove)
+      scope=apps
+      cmd=$arg
+      shift
+      ;;
     --force)
       runtime=sh
       shift
@@ -69,19 +76,19 @@ process:log(){
 
 process:gettmpfile(){
   local pname="${1}"
-  echo /tmp/.pm.$(basename $pname)
+  echo /tmp/.pm.$(basename "$pname")
 }
 
 process:getpidfile(){
   local pname="${1}"
-  echo $(process:gettmpfile $pname).pid
+  echo $(process:gettmpfile "$pname").pid
 }
 
 process:getpid(){
   local pname="${1}"
-  local pidfile=$(process:getpidfile $pname)
-  if [[ -f $pidfile ]]; then
-    cat $pidfile
+  local pidfile=$(process:getpidfile "$pname")
+  if [[ -f "$pidfile" ]]; then
+    cat "$pidfile"
   else 
     echo -1
   fi
@@ -89,37 +96,37 @@ process:getpid(){
 
 process:getlockfile(){
   local pname="${1}"
-  local tmpfile=$(process:gettmpfile $pname)
-  echo $tmpfile.lock
+  local tmpfile=$(process:gettmpfile "$pname")
+  echo "$tmpfile".lock
 }
 
 process:getlogfile(){
   local pname="${1}"
-  local tmpfile=$(process:gettmpfile $pname)
-  echo $tmpfile.log
+  local tmpfile=$(process:gettmpfile "$pname")
+  echo "$tmpfile".log
 }
 
 process:exec(){
   local pname="${1}"
   shift # remove first arg from argument array
   cnt=1
-  lockfile=$(process:getlockfile $pname)
-  trap "process:log \"#$cnt: $pname killed \$?\"; pkill -P $$" EXIT SIGHUP SIGINT SIGTERM
+  lockfile=$(process:getlockfile "$pname")
+  trap "process:log \"#$cnt: "$pname" killed \$?\"; pkill -P $$" EXIT SIGHUP SIGINT SIGTERM
   while :; do
-    process:log "#$cnt $pname started [pid $$]"
-    flock -w 0 $lockfile $pname "$@" || exit 1
+    process:log "#$cnt "$pname" started [pid $$]"
+    flock -w 0 "$lockfile" "$pname" "$@" || exit 1
     code="$?"                                 # check exit status code
     exit="EXIT"
-    if [[ $code == 129 ]]; then
+    if [[ "$code" == 129 ]]; then
       exit=SIGHUP
     fi
-    if [[ $code == 130 ]]; then
+    if [[ "$code" == 130 ]]; then
       exit=SIGINT
     fi
-    if [[ $code == 143 ]]; then
+    if [[ "$code" == 143 ]]; then
       exit=SIGTERM
     fi
-    process:log "#$cnt $pname $exit [$code]"
+    process:log "#$cnt "$pname" "$exit" [$code]"
     sleep 5s                                  # wait for seconds until next boot
     cnt=$(($cnt+1))                           # increment counter
   done
@@ -128,25 +135,25 @@ process:exec(){
 process:start(){
   local pname="${1}"
   shift # remove first arg from argument array
-  pidfile=$(process:gettmpfile $pname).pid
-  logfile=$(process:getlogfile $pname)
-  lockfile=$(process:getlockfile $pname)
-  flock -w 0 $lockfile sleep 0.1s || { echo "already started"; exit 1; }
-  nohup $selfpath/pm exec $pname "$@" 1>$logfile.stdout 2>$logfile.stderr &
-  echo $! > $pidfile 
+  pidfile=$(process:gettmpfile "$pname").pid
+  logfile=$(process:getlogfile "$pname")
+  lockfile=$(process:getlockfile "$pname")
+  flock -w 0 "$lockfile" sleep 0.1s || { echo "already started"; exit 1; }
+  nohup "$selfpath"/pm exec "$pname" "$@" 1>$logfile.stdout 2>$logfile.stderr &
+  echo $! > "$pidfile" 
   echo -e "press CTRL-C to stop logmonitor:\n"
   set -x
-  tailf $logfile.stdout $logfile.stderr
+  tailf "$logfile".stdout "$logfile".stderr
 }
 
 process:stop(){
   local pname="${1}"
   shift # remove first arg
-  pid=$(process:getpid $pname)
-  if [[ ! $pid == "-1" ]]; then
-    echo killing pid $pid 
-    rm $(process:getpidfile $pname)
-    pkill -P $pid
+  pid=$(process:getpid "$pname")
+  if [[ ! "$pid" == "-1" ]]; then
+    echo killing pid "$pid" 
+    rm $(process:getpidfile "$pname")
+    pkill -P "$pid"
   else
     echo "$pname is not running"
   fi
@@ -154,9 +161,9 @@ process:stop(){
 
 process:restart(){
   local pname="${1}"
-  process:stop $pname &
+  process:stop "$pname" &
   wait 
-  process:start $pname
+  process:start "$pname"
 }
 
 process:status(){
@@ -165,40 +172,74 @@ process:status(){
   seen=()
   cols="$(echo "$ps" | head -n1)"                        # print cols header
   printf "%-10s %-10s %s\n" "APP" "STATUS" "$cols"
-  echo "$ps" | grep "flock.*pm\..*\.lock" >> $tmpfile.ps # print psdata
-  for lockfile in $(ls /tmp/.pm.*.lock); do
+  echo "$ps" | grep "flock.*pm\..*\.lock" >> "$tmpfile".ps # print psdata
+  for lockfile in "${ls[@]}" /tmp/.pm.*.lock; do
     appname=${lockfile/*pm\./}
     appname=${appname/\.lock/}
-    echo $appname
-    flock -w 0 $lockfile sleep 0.1s && status=running || status=stopped
-    if [[ $status == "running" ]]; then
+    echo "$appname"
+    flock -w 0 "$lockfile" sleep 0.1s && status=running || status=stopped
+    if [[ "$status" == "running" ]]; then
       printf "%-10s %-10s" "$appname" "$status"
     else
-      line="$(fgrep "$lockfile" $tmpfile.ps)"
+      line="$(fgrep "$lockfile" "$tmpfile".ps)"
       printf "%-10s %-10s %s\n" "$appname" "$status" "$line"
     fi
   done
 }
      
 
+config_file=~/.pm.conf.sh
+tpl_config='
+declare -A apps
+apps=()
+'
+
+apps:init(){
+  if [[ -f "$config_file" ]]; then
+    echo "error: "$config_file" already exist..are you sure? (if so, please delete it)"
+    exit 1
+  else
+    echo "$tpl_config" > "$config_file"
+  fi
+}
+ 
+apps:add(){
+  local appdir="${1}"
+  echo add appdir=$appdir
+}
+
+apps:remove(){
+  local appdir="${1}"
+  echo remove appdir=$appdir
+   
+ }
+
 
 pid=$$
-dependencies="flock awk date sleep ps head"
 
 
 app:init(){
   for dep in "${dependencies[@]}"; do
-    which $dep &>/dev/null || { echo "'$dep' is not installed (pm needs: $dependencies)" && exit 1; }
+    which "$dep" &>/dev/null || { echo "'$dep' is not installed (pm needs: "$dependencies")" && exit 1; }
   done
 }
 
 app:help(){
-  echo 'Usage:
-  pm start <cmd> [args] [..]
-  '
+  echo 'Usage:                                                                                                          '     
+  echo '                                                                                                                '
+  echo '  pm init                                      create ~/.pm.conf.sh configfile                                  '
+  echo '  pm status                                    show app(names) and their status                                 '
+  echo '  pm add <appdir>                              add application(dir which contains application definition file)  '
+  echo '  pm remove <appdir>                           remove application                                               '
+  echo '  pm start <appname> [args] [..]               start app                                                        '
+  echo '  pm stop <appname>                            stop  app                                                        '
+  echo '                                                                                                                '
+  echo '                                               ┌─────────────────────────────────────────────────┐              '
+  echo '                                               │ docs: https://github.com/coderofsalvation/pm.sh │              '
+  echo '                                                                                                                '
 }
 
-app:init && $scope:$cmd "$@"
+app:init && "$scope":$cmd "$@"
 
 # wait for all async child processes (because "await ... then" is used in powscript)
 [[ $ASYNC == 1 ]] && wait
