added dates

diff --git a/bin/pm b/bin/pm
--- a/bin/pm
+++ b/bin/pm
@@ -5,15 +5,20 @@
 # Unless you like pain: edit the .pow sourcefiles instead of this file
 
 # powscript general settings
-set -e                         # halt on error
-set +m                         #
-SHELL="$(echo $0)"             # shellname
-SHELLNAME="$(basename $SHELL)" # shellname without path
-shopt -s lastpipe              # flexible while loops (maintain scope)
-shopt -s extglob               # regular expressions
+set -e                                # halt on error
+set +m                                #
+SHELL="$(echo $0)"                    # shellname
+shopt -s lastpipe                     # flexible while loops (maintain scope)
+shopt -s extglob                      # regular expressions
 path="$(pwd)"
-selfpath="$( dirname "$(readlink -f "$0")" )"
-tmpfile="/tmp/$(basename $0).tmp.$(whoami)"
+if [[ "$BASH_SOURCE" == "$0"  ]];then #
+  SHELLNAME="$(basename $SHELL)"      # shellname without path
+  selfpath="$( dirname "$(readlink -f "$0")" )"
+  tmpfile="/tmp/$(basename $0).tmp.$(whoami)"
+else
+  selfpath="$path"
+  tmpfile="/tmp/.dot.tmp.$(whoami)"
+fi
 #
 # generated by powscript (https://github.com/coderofsalvation/powscript)
 #
@@ -358,7 +363,7 @@ process:tail(){
   apps:exit_if_nonexists $appname
   deffile=$(process:gettmpfile $appname).def
   logfile=$(process:getlogfile $appname)
-  echo -e "press CTRL-C to stop logmonitor:\n"
+  echo -e "$(date) press CTRL-C to stop logmonitor:\n"
   tail -q -f $logfile.*
 }
 
@@ -728,7 +733,7 @@ server:gitpull(){
   workdir=$(apps:getworkdir $deffile)
   if [[ -d $workdir/.git ]]; then
     cd $workdir
-    echo -e "received webhook: pull $appname, performing git pull"
+    echo -e "$(date) received webhook: pull $appname, performing git pull"
     set +e
     $selfpath/pm stop $appname
     branchname="$( git branch 2>&1 | grep "^*" | sed 's/ //g;s/^*//g'    )"
@@ -804,9 +809,9 @@ app:init && $scope:$cmd "$@"
 
 
 # cleanup tmp files
-if ls /tmp/$(basename $0).tmp.sqz* &>/dev/null; then
+if ls /tmp/$(basename $0).tmp.sqz*; then
   for f in /tmp/$(basename $0).tmp.sqz*; do rm $f; done
-fi
+fi &>/dev/null
 
 exit 0
 
